import { Injectable, computed, signal } from '@angular/core';
import { Emoji } from '../models/emoji.model';
import { EMOJI_DATA } from '../data/emoji-data';

const ES_TRANSLATIONS: Record<string, string[]> = {
  // Smileys
  smile: ['sonrisa','sonreir','feliz'],
  happy: ['feliz','contento','alegre'],
  laugh: ['risa','reir','carcajada','jaja'],
  cry: ['llorar','llanto','lagrima'],
  tears: ['lagrimas'],
  sad: ['triste','tristeza'],
  angry: ['enojado','enojo','furioso','rabia'],
  mad: ['enojado','furioso'],
  love: ['amor','querer','amar','corazon'],
  kiss: ['beso','besar'],
  heart: ['corazon'],
  wink: ['guino','guiño'],
  shy: ['timido','vergüenza'],
  think: ['pensar','pensando'],
  sleep: ['dormir','sueño','dormido'],
  sick: ['enfermo','enfermedad'],
  cool: ['genial','chevere'],
  crazy: ['loco','locura'],
  scared: ['miedo','asustado','susto'],
  surprise: ['sorpresa','sorprendido'],
  shock: ['shock','impacto'],
  devil: ['diablo','demonio'],
  evil: ['malvado','malo'],
  ghost: ['fantasma'],
  skull: ['calavera','muerte'],
  robot: ['robot'],
  clown: ['payaso'],
  poop: ['caca','mierda','popó'],
  party: ['fiesta','celebrar'],
  nerd: ['nerd','cerebrito'],
  // People
  hand: ['mano','manos'],
  wave: ['ola','saludar','saludo'],
  hello: ['hola'],
  bye: ['adios','chao'],
  stop: ['parar','alto','detener'],
  point: ['señalar','apuntar','dedo'],
  finger: ['dedo'],
  thumb: ['pulgar','dedo'],
  thumbs: ['pulgar'],
  fist: ['puño'],
  punch: ['puñetazo','golpe'],
  strong: ['fuerte','fuerza'],
  muscle: ['musculo','brazo'],
  clap: ['aplaudir','aplauso'],
  pray: ['rezar','orar','por favor'],
  write: ['escribir'],
  ear: ['oreja','oido'],
  nose: ['nariz'],
  eye: ['ojo'],
  eyes: ['ojos'],
  tongue: ['lengua'],
  mouth: ['boca','labios'],
  foot: ['pie'],
  leg: ['pierna'],
  ok: ['ok','bien','perfecto'],
  victory: ['victoria','paz'],
  left: ['izquierda'],
  right: ['derecha'],
  up: ['arriba'],
  down: ['abajo'],
  baby: ['bebe','bebé'],
  boy: ['niño','chico'],
  girl: ['niña','chica'],
  man: ['hombre'],
  woman: ['mujer'],
  old: ['viejo','anciano','abuelo'],
  police: ['policia'],
  ninja: ['ninja'],
  prince: ['principe'],
  princess: ['princesa'],
  angel: ['angel'],
  santa: ['papa noel','navidad'],
  hero: ['heroe','superheroe'],
  facepalm: ['facepalm','verguenza'],
  shrug: ['no se','ni idea'],
  // Animals
  dog: ['perro','can'],
  puppy: ['cachorro','perrito'],
  cat: ['gato','gatito'],
  mouse: ['raton','ratón'],
  rabbit: ['conejo'],
  bunny: ['conejito'],
  fox: ['zorro'],
  bear: ['oso'],
  panda: ['panda','oso panda'],
  lion: ['leon','león'],
  tiger: ['tigre'],
  monkey: ['mono','chango'],
  horse: ['caballo'],
  cow: ['vaca'],
  pig: ['cerdo','chancho','puerco'],
  chicken: ['pollo','gallina'],
  bird: ['pajaro','pájaro','ave'],
  fish: ['pez','pescado'],
  whale: ['ballena'],
  dolphin: ['delfin','delfín'],
  shark: ['tiburon','tiburón'],
  snake: ['serpiente','vibora'],
  butterfly: ['mariposa'],
  bee: ['abeja'],
  spider: ['araña'],
  turtle: ['tortuga'],
  frog: ['rana','sapo'],
  dragon: ['dragon','dragón'],
  unicorn: ['unicornio'],
  flower: ['flor'],
  rose: ['rosa'],
  tree: ['arbol','árbol'],
  // Food
  apple: ['manzana'],
  banana: ['banana','platano','plátano'],
  orange: ['naranja','anaranjado'],
  lemon: ['limon','limón'],
  grape: ['uva','uvas'],
  watermelon: ['sandia','sandía'],
  strawberry: ['fresa','frutilla'],
  peach: ['durazno','melocoton'],
  mango: ['mango'],
  pineapple: ['piña','ananá'],
  tomato: ['tomate'],
  avocado: ['aguacate','palta'],
  corn: ['maiz','maíz','elote'],
  carrot: ['zanahoria'],
  potato: ['papa','patata'],
  bread: ['pan'],
  cheese: ['queso'],
  meat: ['carne'],
  burger: ['hamburguesa'],
  pizza: ['pizza'],
  taco: ['taco'],
  burrito: ['burrito'],
  egg: ['huevo'],
  rice: ['arroz'],
  pasta: ['pasta','fideos'],
  sushi: ['sushi'],
  cake: ['torta','pastel'],
  cookie: ['galleta'],
  candy: ['dulce','caramelo'],
  chocolate: ['chocolate'],
  coffee: ['cafe','café'],
  tea: ['te','té'],
  beer: ['cerveza','birra'],
  wine: ['vino'],
  water: ['agua'],
  ice: ['hielo','helado'],
  // Travel
  car: ['auto','carro','coche'],
  taxi: ['taxi'],
  bus: ['bus','autobus'],
  truck: ['camion','camión'],
  bike: ['bicicleta','bici'],
  motorcycle: ['moto','motocicleta'],
  airplane: ['avion','avión'],
  plane: ['avion','avión'],
  rocket: ['cohete'],
  boat: ['barco','bote'],
  ship: ['barco','crucero'],
  train: ['tren'],
  house: ['casa','hogar'],
  school: ['escuela','colegio'],
  hospital: ['hospital'],
  church: ['iglesia'],
  mountain: ['montaña','cerro'],
  beach: ['playa'],
  island: ['isla'],
  sun: ['sol'],
  moon: ['luna'],
  star: ['estrella'],
  rain: ['lluvia'],
  snow: ['nieve'],
  fire: ['fuego','llama','flama'],
  rainbow: ['arcoiris','arco iris'],
  ocean: ['oceano','océano','mar'],
  // Activities
  soccer: ['futbol','fútbol'],
  basketball: ['basquet','basquetbol'],
  tennis: ['tenis'],
  swim: ['nadar','natacion'],
  sport: ['deporte'],
  gym: ['gimnasio'],
  yoga: ['yoga'],
  surf: ['surf','surfear'],
  climb: ['escalar','escalada'],
  run: ['correr'],
  game: ['juego','videojuego'],
  music: ['musica','música'],
  guitar: ['guitarra'],
  piano: ['piano'],
  sing: ['cantar'],
  movie: ['pelicula','película','cine'],
  art: ['arte','pintura'],
  paint: ['pintar','pintura'],
  dance: ['bailar','baile'],
  trophy: ['trofeo','premio'],
  medal: ['medalla'],
  celebrate: ['celebrar','celebracion'],
  birthday: ['cumpleaños'],
  gift: ['regalo'],
  christmas: ['navidad'],
  halloween: ['halloween'],
  // Objects
  phone: ['telefono','teléfono','celular'],
  computer: ['computadora','computador','ordenador','pc'],
  laptop: ['laptop','portatil','portátil'],
  camera: ['camara','cámara','foto'],
  tv: ['television','televisor','tele'],
  money: ['dinero','plata'],
  key: ['llave'],
  lock: ['candado','cerradura'],
  tool: ['herramienta'],
  book: ['libro'],
  email: ['correo','email'],
  trash: ['basura'],
  pill: ['pastilla','pildora'],
  bomb: ['bomba'],
  crown: ['corona'],
  ring: ['anillo'],
  glasses: ['lentes','gafas'],
  shoe: ['zapato','zapatilla'],
  hat: ['sombrero','gorro'],
  // More objects
  scissors: ['tijeras'],
  pencil: ['lapiz','lápiz'],
  pen: ['lapicera','boligrafo'],
  folder: ['carpeta'],
  package: ['paquete','caja'],
  cart: ['carrito','compras'],
  shield: ['escudo'],
  sword: ['espada'],
  swords: ['espadas'],
  teddy: ['peluche','osito'],
  dress: ['vestido'],
  backpack: ['mochila'],
  lipstick: ['labial','maquillaje'],
  science: ['ciencia'],
  dna: ['adn','genetica'],
  // More food
  soup: ['sopa','caldo'],
  salad: ['ensalada'],
  noodles: ['fideos','tallarines'],
  shrimp: ['camaron','camarón','gamba'],
  donut: ['dona','rosquilla'],
  popcorn: ['palomitas'],
  butter: ['mantequilla','manteca'],
  salt: ['sal'],
  spicy: ['picante'],
  sweet: ['dulce'],
  delicious: ['delicioso','rico','sabroso'],
  hungry: ['hambre','hambriento'],
  drink: ['bebida','tomar','beber'],
  cocktail: ['coctel','cóctel','trago'],
  champagne: ['champagne','champaña'],
  juice: ['jugo','zumo'],
  // More animals
  elephant: ['elefante'],
  giraffe: ['jirafa'],
  zebra: ['cebra'],
  gorilla: ['gorila'],
  camel: ['camello'],
  kangaroo: ['canguro'],
  deer: ['ciervo','venado'],
  owl: ['buho','búho','lechuza'],
  eagle: ['aguila','águila'],
  duck: ['pato'],
  penguin: ['pinguino','pingüino'],
  parrot: ['loro','cotorra'],
  flamingo: ['flamenco'],
  swan: ['cisne'],
  wolf: ['lobo'],
  bat: ['murcielago','murciélago'],
  scorpion: ['escorpion','escorpión','alacran'],
  snail: ['caracol'],
  ant: ['hormiga'],
  mosquito: ['mosquito','zancudo'],
  worm: ['gusano'],
  octopus: ['pulpo'],
  squid: ['calamar'],
  crocodile: ['cocodrilo'],
  lizard: ['lagartija','lagarto'],
  hedgehog: ['erizo'],
  otter: ['nutria'],
  sloth: ['perezoso'],
  beaver: ['castor'],
  llama: ['llama','alpaca'],
  goat: ['cabra','chivo'],
  sheep: ['oveja'],
  hippo: ['hipopotamo','hipopótamo'],
  rhino: ['rinoceronte'],
  cactus: ['cactus'],
  clover: ['trebol','trébol','suerte'],
  leaf: ['hoja'],
  plant: ['planta'],
  herb: ['hierba'],
  // More travel
  volcano: ['volcan','volcán'],
  globe: ['globo','mundo','planeta'],
  weather: ['clima','tiempo'],
  storm: ['tormenta'],
  thunder: ['trueno','rayo'],
  wind: ['viento'],
  cold: ['frio','frío'],
  hot: ['calor','caliente'],
  cloud: ['nube','nublado'],
  // More activities
  boxing: ['boxeo'],
  karate: ['karate'],
  archery: ['tiro con arco'],
  fishing: ['pesca','pescar'],
  bowling: ['boliche','bolos'],
  chess: ['ajedrez'],
  dice: ['dado','dados'],
  target: ['diana','objetivo'],
  dart: ['dardo'],
  casino: ['casino'],
  fireworks: ['fuegos artificiales'],
  balloon: ['globo'],
  // More people
  child: ['niño','niña','hijo','hija'],
  adult: ['adulto'],
  elder: ['anciano','abuelo','abuela'],
  beard: ['barba'],
  blonde: ['rubio','rubia'],
  guard: ['guardia'],
  construction: ['construccion','obrero'],
  royal: ['real','realeza'],
  king: ['rey'],
  queen: ['reina'],
  mage: ['mago'],
  wizard: ['mago','hechicero'],
  fairy: ['hada'],
  mermaid: ['sirena'],
  vampire: ['vampiro'],
  magic: ['magia','magico'],
  deaf: ['sordo'],
  bow: ['reverencia','disculpa'],
  // Symbols
  check: ['check','correcto','si','listo'],
  no: ['no','incorrecto'],
  warning: ['advertencia','cuidado','peligro'],
  question: ['pregunta'],
  exclamation: ['exclamacion'],
  infinity: ['infinito'],
  recycle: ['reciclar','reciclaje'],
  play: ['reproducir'],
  pause: ['pausa'],
  shuffle: ['aleatorio','mezclar'],
  repeat: ['repetir'],
  plus: ['mas','sumar'],
  minus: ['menos','restar'],
  divide: ['dividir'],
  multiply: ['multiplicar'],
  copyright: ['derechos'],
  trademark: ['marca'],
  note: ['nota'],
  notes: ['notas'],
  red: ['rojo'],
  blue: ['azul'],
  green: ['verde'],
  yellow: ['amarillo'],
  purple: ['morado','violeta'],
  black: ['negro'],
  white: ['blanco'],
  brown: ['marron','marrón','cafe'],
  pink: ['rosa','rosado'],
  grey: ['gris'],
  // Flags
  flag: ['bandera'],
  argentina: ['argentina'],
  brazil: ['brasil'],
  mexico: ['mexico','méxico'],
  spain: ['españa','espana'],
  colombia: ['colombia'],
  chile: ['chile'],
  peru: ['peru','perú'],
  venezuela: ['venezuela'],
  usa: ['estados unidos','eeuu'],
  france: ['francia'],
  germany: ['alemania'],
  italy: ['italia'],
  japan: ['japon','japón'],
  china: ['china'],
  korea: ['corea'],
  india: ['india'],
};

@Injectable({ providedIn: 'root' })
export class EmojiSearchService {
  private readonly index = new Map<string, Set<number>>();
  private readonly emojis = EMOJI_DATA;

  readonly query = signal('');

  readonly results = computed<Emoji[]>(() => {
    const q = this.query().trim().toLowerCase();
    if (!q) return [];

    const tokens = q.split(/\s+/);
    let matchedIndices: Set<number> | null = null;

    for (const token of tokens) {
      const tokenMatches = new Set<number>();
      for (const [key, indices] of this.index) {
        if (key.includes(token)) {
          for (const i of indices) {
            tokenMatches.add(i);
          }
        }
      }
      if (matchedIndices === null) {
        matchedIndices = tokenMatches;
      } else {
        for (const i of matchedIndices) {
          if (!tokenMatches.has(i)) {
            matchedIndices.delete(i);
          }
        }
      }
      if (matchedIndices.size === 0) return [];
    }

    return matchedIndices ? Array.from(matchedIndices).map(i => this.emojis[i]) : [];
  });

  constructor() {
    this.buildIndex();
  }

  private buildIndex(): void {
    for (let i = 0; i < this.emojis.length; i++) {
      const emoji = this.emojis[i];
      const terms = [
        ...emoji.name.toLowerCase().split(/[\s_-]+/),
        ...emoji.keywords.map(k => k.toLowerCase()),
      ];

      // Add Spanish translations
      for (const term of [...terms]) {
        const translations = ES_TRANSLATIONS[term];
        if (translations) {
          terms.push(...translations);
        }
      }

      for (const term of terms) {
        if (!term) continue;
        const set = this.index.get(term);
        if (set) {
          set.add(i);
        } else {
          this.index.set(term, new Set([i]));
        }
      }
    }
  }
}
